name: Deployment workflow
on:
  push:
    branches: [ main ]

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

  Deploy:
    runs-on: self-hosted
    needs: [checkout]
    steps:
      - name: create venv
        run: |
          rm -rf venv
          python3 -m venv venv
          source venv/bin/activate
          pip3 install flask gunicorn
          pip3 install -r requirements.txt

  Start-server:
    runs-on: self-hosted
    needs: [Deploy]
    steps:
      - name: Start-server
        run: |
          source venv/bin/activate
